## MYSQL
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dw_501
    username: root
    password: '06251003'
  jpa:
    database: mysql
    generate-ddl: true
    ddl-auto: update
    show-sql: true
    format_sql: true
